[ttio]

scan=0x36
card_id=1234567890123456

# https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes


# enter
key10=0x31
# select
key11=0x32
# test
key12=0x33
# service
key13=0x34
# coin
key15=0x35

[aime]
enable=0
port=4
high_baudrate=1
custom_led_flash=0

[api]
enable=0
groupId=1
deviceId=1
bindAddr=255.255.255.255
port=5364
log=1

serviceButtonIndex=13
testButtonIndex=12
coinButtonIndex=15
