[ttio]

# card ID that will be scanned
card_id=1234567890123456

# Key bindings
# from key0 to key31, buttons mapped to I/O pins.
# https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

# scan card
scan=0x36
# enter
key10=0x31
# select
key11=0x32
# test
key12=0x33
# service
key13=0x34
# coin
key15=0x35

[aime]
# Use a real Aime reader instead of NESiCA emulation?
enable=0
# COM port for the Aime reader
port=4
# Use high baud rate? Usually on.
high_baudrate=1
# Use custom LED flashing (as opposed to controlled by the game)
custom_led_flash=0

# LED bindings
# Indexes in the output data where NESiCA reader RGB values are sent.
led_index_r=9
led_index_g=10
led_index_b=11

read_delay=1000
read_timeout=0

[api]
# Enable SegAPI / segatools API?
enable=0
# Group ID
groupId=1
# Device ID
deviceId=1
# Broadcast address for data
bindAddr=255.255.255.255
# Port
port=5364
# Logging enabled?
log=1

# JVS button to be pressed (same indexes as [ttio] buttons) when service/test/coin is received from the API
serviceButtonIndex=13
testButtonIndex=12
coinButtonIndex=15
